# Tables for experiment 3 (DC-OTS paper test cases).
#   julia --project=. scripts/analyze_experiment3.jl
using JSON, Printf

const RES = joinpath(@__DIR__, "..", "results")
const CASES = ["3-lmbd-api", "5-pjm-api", "14-ieee-api", "24-ieee-rts-api", "30-as-api", "30-ieee-api", "39-epri-api",
    "57-ieee-api", "60-c-api", "73-ieee-rts-api", "89-pegase-api", "118-ieee-api", "179-goc-api", "200-activ-api",
    "240-pserc-api", "300-ieee-api", "500-goc-api", "1354-pegase-api"]
const VARIANTS = ["mixed", "mixed_nobigM", "adj16", "adj16_pairs"]
const SCHEMES = ["threshold", "independent", "gaussian", "conditional"]

f2(x) = x === nothing ? "–" : @sprintf("%.2f", x)
pct(x) = x === nothing ? "–" : @sprintf("%.2f%%", 100x)
gap(c, ref) = c === nothing ? "–" : @sprintf("%+.2f%%", 100(c - ref) / ref)

# A lower bound above a known feasible cost is impossible. Rather than tabulate such a number, mark the row
# and fail at the end: 1354-pegase reported 2.58e6-3.77e6 against a known feasible 1.498e6 for a whole week
# because nothing checked. See results/merging_findings.md.
bestknown(r) = minimum(filter(!isnothing, [r["best_found"], r["paper_acots"], r["paper_odcots"]]))
valid(x, bk) = x === nothing || !isfinite(x) || x <= bk + 1e-6 * max(abs(bk), 1.0)
const INVALID = String[]

io = IOBuffer()
println(io, "# Experiment 3 tables: DC-OTS paper test cases\n")
println(io, "*Generated by `scripts/analyze_experiment3.jl`. Costs in \$/h. \"paper\" columns are from Taheri & Molzahn, Table II (AC-OTS = PowerModels + Juniper, local). Gaps of our solutions are relative to the paper's AC-OTS cost (negative = better). Certified gap = (best known − best certified bound) / best known, where best known = min(ours, paper AC-OTS, paper O-DC-OTS).*\n")

println(io, "## Summary\n")
println(io, "| case | AC-OPF | paper O-DC-OTS | paper AC-OTS | best found (ours) | vs paper AC-OTS | best certified bound | certified gap | configs evaluated |")
println(io, "|---|---|---|---|---|---|---|---|---|")
files = Dict(c => joinpath(RES, "experiment3_$(c).json") for c in CASES)
for c in CASES
    isfile(files[c]) || continue
    r = JSON.parsefile(files[c])
    haskey(r, "best_found") || continue
    ref = something(r["paper_acots"], r["paper_odcots"])
    # best known: ours, paper AC-OTS, or the paper's O-DC-OTS topology (Table II reports its AC cost)
    bk = bestknown(r)
    ok = valid(r["best_bound"], bk)
    ok || push!(INVALID, "$c (summary best_bound $(f2(r["best_bound"])) > best known $(f2(bk)))")
    cg = (r["best_bound"] === nothing || !ok) ? nothing : (bk - r["best_bound"]) / bk
    @printf(io, "| %s | %.2f | %d | %s | %.2f | %s | %s | %s | %d |\n", c, r["acopf"], r["paper_odcots"],
        something(r["paper_acots"], "–"), r["best_found"], gap(r["best_found"], ref),
        ok ? f2(r["best_bound"]) : "**INVALID**", pct(cg), r["n_configs_evaluated"])
end

println(io, "\n## Relaxations\n")
println(io, "| case | variant | status | certified bound | raw bound | correction | time (s) | order-2 cliques | max PSD | integral marginals | marginals < 0.5 |")
println(io, "|---|---|---|---|---|---|---|---|---|---|---|")
for c in CASES
    isfile(files[c]) || continue
    r = JSON.parsefile(files[c])
    for v in VARIANTS
        haskey(r["relaxations"], v) || continue
        o = r["relaxations"][v]
        if get(o, "failed", false)
            @printf(io, "| %s | %s | FAILED | | | | %.1f | | | | |\n", c, v, o["time"])
            continue
        end
        nob = o["bound"] === nothing || o["raw_bound"] === nothing
        vok = !haskey(r, "best_found") || valid(o["bound"], bestknown(r))
        vok || push!(INVALID, "$c/$v (bound $(f2(o["bound"])) > best known $(f2(bestknown(r))))")
        @printf(io, "| %s | %s | %s | %s | %s | %s | %.1f | %d/%d | %d | %.0f%% | %d |\n", c, v, o["status"],
            !vok ? "**INVALID**" : o["bound"] === nothing ? "none (no feasible SOS point)" : f2(o["bound"]),
            f2(o["raw_bound"]), nob ? "–" : @sprintf("%.2f", o["raw_bound"] - o["bound"]), o["time"],
            o["n_order2"], o["n_cliques"], o["max_psd"], 100o["frac_integral"], o["n_marg_below_half"])
    end
end

println(io, "\n## Rounding (best cost per scheme, gap vs paper AC-OTS; feasible fraction in parentheses)\n")
println(io, "| case | variant | threshold | independent | gaussian | conditional | best rounded | after 1-flip polish (evals) |")
println(io, "|---|---|---|---|---|---|---|---|")
for c in CASES
    isfile(files[c]) || continue
    r = JSON.parsefile(files[c])
    ref = something(r["paper_acots"], r["paper_odcots"])
    for v in VARIANTS
        haskey(r["relaxations"], v) || continue
        o = r["relaxations"][v]
        get(o, "failed", false) && continue
        haskey(o, "polished") || continue
        cells = [@sprintf("%s (%.0f%%)", gap(o["schemes"][s]["best"], ref), 100o["schemes"][s]["feas"]) for s in SCHEMES]
        @printf(io, "| %s | %s | %s | %s | %s (%d) |\n", c, v, join(cells, " | "), gap(o["best_rounded"], ref),
            gap(o["polished"], ref), o["polish_evals"])
    end
end

out = joinpath(RES, "experiment3_tables.md")
write(out, String(take!(io)))
println("wrote ", out)

if !isempty(INVALID)
    for s in INVALID
        println(stderr, "  INVALID BOUND: ", s)
    end
    error("$(length(INVALID)) bound(s) exceed a known feasible cost and were written as **INVALID**. " *
          "A lower bound cannot exceed a feasible solution: the relaxation is not a relaxation of this " *
          "problem. Diagnose before reporting (see results/merging_findings.md).")
end
