# Build results/experiment1_tables.md from results/experiment1_<instance>.json and results/enum_<instance>.json.
#   julia --project=. scripts/analyze_experiment1.jl
using JSON, Printf

const RES = joinpath(@__DIR__, "..", "results")
const TOL = 1e-5          # relative tolerance for "optimal" (Ipopt solutions agree to ~1e-6)
const SCHEMES = ["threshold", "independent", "gaussian", "conditional", "dive"]

pct(x) = @sprintf("%.0f%%", 100x)

function load_costs(name)
    js = JSON.parsefile(joinpath(RES, "enum_$(name).json"))
    Dict(r["bits"] => (r["cost"] === nothing ? Inf : Float64(r["cost"])) for r in js["configs"]), js
end

function scheme_stats(counts, costs, opt)
    n = sum(values(counts))
    feas = sum((c for (b, c) in counts if isfinite(costs[b])); init = 0) / n
    popt = sum((c for (b, c) in counts if costs[b] <= opt * (1 + TOL)); init = 0) / n
    p1 = sum((c for (b, c) in counts if costs[b] <= opt * 1.01); init = 0) / n
    return n, length(counts), feas, popt, p1, 1 - (1 - popt)^10
end

io = IOBuffer()
names = [f[13:end-5] for f in readdir(RES) if startswith(f, "experiment1_") && endswith(f, ".json")]
order_pref = ["case5_uc", "case5_uc_sym", "case14_uc", "case5_ots", "case9_ots"]
sort!(names; by = n -> something(findfirst(==(n), order_pref), 99))

println(io, "# Experiment 1 tables (generated by scripts/analyze_experiment1.jl)\n")
println(io, "\"Optimal\" means within $(TOL) relative of the best enumerated configuration. P(opt in 10) = 1 − (1 − p)^10 for i.i.d. draws.\n")
println(io, "## Relaxation bounds\n")
println(io, "| instance | binaries | feasible configs | opt | order-1 bound (gap) | order-1 time | order-2 bound (gap) | order-2 time | order-2 status |")
println(io, "|---|---|---|---|---|---|---|---|---|")
for name in names
    ex = JSON.parsefile(joinpath(RES, "experiment1_$(name).json"))
    costs, en = load_costs(name)
    nfeas = count(isfinite, values(costs))
    o1, o2 = ex["orders"]["1"], ex["orders"]["2"]
    @printf(io, "| %s | %d | %d / %d | %.2f | %.2f (%.2f%%) | %.2fs | %.2f (%.3f%%) | %.1fs | %s |\n", name, length(ex["binaries"]),
        nfeas, length(costs), ex["opt"], o1["bound"], 100o1["gap"], o1["solve_time"], o2["bound"], 100o2["gap"],
        o2["solve_time"], o2["status"])
end

for name in names
    ex = JSON.parsefile(joinpath(RES, "experiment1_$(name).json"))
    costs, en = load_costs(name)
    opt = ex["opt"]
    println(io, "\n## $(name)\n")
    println(io, en["description"], "  \nbinaries: ", join(ex["binaries"], ", "), "  \n")
    ranked = sort([(b, c) for (b, c) in costs if isfinite(c)]; by = last)
    println(io, "Best configurations: ", join([@sprintf("`%s` %.2f (+%.3f%%)", b, c, 100(c / opt - 1)) for (b, c) in ranked[1:min(5, end)]], ", "), "\n")
    println(io, "| order | scheme | samples | unique | feasible | optimal | ≤1% | P(opt in 10) | time (s) |")
    println(io, "|---|---|---|---|---|---|---|---|---|")
    for ord in ("1", "2"), sch in SCHEMES
        s = ex["orders"][ord]["schemes"][sch]
        n, u, f, p, p1, p10 = scheme_stats(s["config_counts"], costs, opt)
        extra = haskey(s, "sdp_solves") ? " ($(s["sdp_solves"]) SDPs)" : ""
        @printf(io, "| %s | %s | %d | %d | %s | %s | %s | %s | %.1f%s |\n", ord, sch, n, u, pct(f), pct(p), pct(p1), pct(p10), s["time"], extra)
    end
    for ord in ("1", "2")
        o = ex["orders"][ord]
        println(io, "\nOrder $ord marginals: ", join([@sprintf("%.3f", m) for m in o["marginals"]], ", "))
        R = o["corr"]
        println(io, "\nOrder $ord binary correlation matrix (from pseudo-moments):\n\n```")
        for row in R
            println(io, join([@sprintf("%6.2f", x) for x in row], " "))
        end
        println(io, "```")
        println(io, "\nOrder $ord sampled configurations (count, cost gap):\n")
        for sch in SCHEMES
            cc = sort(collect(ex["orders"][ord]["schemes"][sch]["config_counts"]); by = x -> -x[2])
            items = [@sprintf("`%s`×%d (%s)", b, c, isfinite(costs[b]) ? @sprintf("+%.3f%%", 100(costs[b] / opt - 1)) : "infeas.")
                     for (b, c) in cc[1:min(6, end)]]
            println(io, "- $sch: ", join(items, ", "))
        end
    end
end

out = joinpath(RES, "experiment1_tables.md")
write(out, String(take!(io)))
println("wrote ", out)
