# Build results/experiment2_tables.md from results/experiment2*_<instance>.json.
#   julia --project=. scripts/analyze_experiment2.jl
using JSON, Printf

const RES = joinpath(@__DIR__, "..", "results")
files = sort([f for f in readdir(RES) if startswith(f, "experiment2") && endswith(f, ".json")])
data = Dict{String,Vector{Any}}()
for f in files
    js = JSON.parsefile(joinpath(RES, f))
    push!(get!(data, js["instance"], Any[]), js)
end
order_pref = ["case14_ots", "case30_uc", "case24_uc", "case30_ots", "case24_ots"]
names = sort(collect(keys(data)); by = n -> something(findfirst(==(n), order_pref), 99))

fmt(x) = x === nothing ? "–" : @sprintf("%.2f", x)
gap(c, b) = (c === nothing || b === nothing) ? "–" : @sprintf("%.2f%%", 100(c - b) / c)

io = IOBuffer()
println(io, "# Experiment 2 tables (generated by scripts/analyze_experiment2.jl)\n")
println(io, "Gaps are relative to the best configuration found for the instance across all runs (or the enumerated optimum).\n")
println(io, "| instance | vars | bin | all-on | NLP relax-and-round best | best known | best bound | certified gap |")
println(io, "|---|---|---|---|---|---|---|---|")
bestknown = Dict{String,Float64}()
bestbound = Dict{String,Float64}()
for n in names
    runs = data[n]
    bk = minimum(r["best_found"] for r in runs)
    haskey(runs[1], "enumerated_opt") && (bk = min(bk, runs[1]["enumerated_opt"]))
    bb = maximum(o["bound"] for r in runs for o in values(r["relaxations"]))
    bestknown[n], bestbound[n] = bk, bb
    nlp = runs[1]["nlp_relax_round"]
    nlpbest = minimum(filter(!isnothing, [get(nlp, "threshold_cost", nothing), get(nlp, "independent_best", nothing)]); init = Inf)
    @printf(io, "| %s | %d | %d | %s | %s | %.2f | %.2f | %.2f%% |\n", n, runs[1]["n_vars"], runs[1]["n_binaries"],
        fmt(runs[1]["all_on"]), isfinite(nlpbest) ? @sprintf("%.2f", nlpbest) : "–", bk, bb, 100(bk - bb) / bk)
end

println(io, "\n## Relaxation variants\n")
println(io, "| instance | variant | bound (gap to best known) | status | time (s) | order-2 cliques | max PSD | pair moments | integral marginals | best rounded (gap) by scheme: thr / ind / gauss / cond | feasible % (ind / gauss / cond) |")
println(io, "|---|---|---|---|---|---|---|---|---|---|---|")
for n in names, r in data[n]
    for (lbl, o) in sort(collect(r["relaxations"]); by = first)
        sc = o["schemes"]
        bests = join([sc[s]["best"] === nothing ? "infeas." : gap(sc[s]["best"], bestknown[n]) for s in ("threshold", "independent", "gaussian", "conditional")], " / ")
        feas = join([@sprintf("%.0f", 100sc[s]["feas"]) for s in ("independent", "gaussian", "conditional")], " / ")
        @printf(io, "| %s | %s | %.2f (%s) | %s | %.1f | %d / %d | %d | %d/%d | %.0f%% | %s | %s |\n", n, lbl, o["bound"],
            gap(bestknown[n], o["bound"]), o["status"], o["time"], o["n_order2"], o["n_cliques"], o["max_psd"],
            o["pair_moments"][1], o["pair_moments"][2], 100o["frac_integral"], bests, feas)
    end
end
out = joinpath(RES, "experiment2_tables.md")
write(out, String(take!(io)))
println("wrote ", out)
