# Compare rounding experiments before/after the numerics changes (normalize + scale_vars, certified bounds).
#   OLD_DIR=<dir with previous JSON results> julia --project=. scripts/compare_rerun.jl
using JSON, Printf

const RES = joinpath(@__DIR__, "..", "results")
const OLD = ENV["OLD_DIR"]
const TOL = 1e-5
pct(x) = x === nothing ? "–" : @sprintf("%.0f%%", 100x)
f2(x) = x === nothing ? "–" : @sprintf("%.2f", x)

enumcosts(name) = (js = JSON.parsefile(joinpath(RES, "enum_$(name).json"));
    Dict(r["bits"] => (r["cost"] === nothing ? Inf : Float64(r["cost"])) for r in js["configs"]))
function optrate(counts, costs, opt)
    n = sum(values(counts))
    return sum((c for (b, c) in counts if costs[b] <= opt * (1 + TOL)); init = 0) / n
end

io = IOBuffer()
println(io, "# Rounding experiments before vs after the numerics changes\n")
println(io, "*Generated by `scripts/compare_rerun.jl`. \"old\" = results at commit d200dbb (unnormalized relaxations, raw SOS bounds); \"new\" = rerun with `normalize = true`, `scale_vars = true`, certified bounds. Same seeds and sample counts.*\n")

println(io, "## Experiment 1 (enumerable instances)\n")
println(io, "\"opt\" = fraction of samples that are optimal (within 1e-5).\n")
println(io, "| instance | order | bound old → new | marginals old | marginals new | threshold opt | independent opt | gaussian opt | conditional opt | dive opt |")
println(io, "|---|---|---|---|---|---|---|---|---|---|")
for name in ["case5_uc", "case5_uc_sym", "case14_uc", "case5_ots", "case9_ots"]
    fo, fn = joinpath(OLD, "experiment1_$(name).json"), joinpath(RES, "experiment1_$(name).json")
    (isfile(fo) && isfile(fn)) || continue
    o, n = JSON.parsefile(fo), JSON.parsefile(fn)
    costs = enumcosts(name)
    opt = n["opt"]
    for ord in ("1", "2")
        oo, nn = o["orders"][ord], n["orders"][ord]
        rates = join([@sprintf("%s → %s", pct(optrate(oo["schemes"][s]["config_counts"], costs, opt)),
                          pct(optrate(nn["schemes"][s]["config_counts"], costs, opt)))
                      for s in ("threshold", "independent", "gaussian", "conditional", "dive")], " | ")
        @printf(io, "| %s | %s | %.2f → %.2f | %s | %s | %s |\n", name, ord, oo["bound"], nn["bound"],
            join([@sprintf("%.2f", m) for m in oo["marginals"]], " "), join([@sprintf("%.2f", m) for m in nn["marginals"]], " "), rates)
    end
end

fo, fn = joinpath(OLD, "experiment1b_cliques.json"), joinpath(RES, "experiment1b_cliques.json")
if isfile(fo) && isfile(fn)
    o, n = JSON.parsefile(fo), JSON.parsefile(fn)
    println(io, "\n## Experiment 1b (clique augmentation, order 2)\n")
    println(io, "| instance | variant | bound old → new | pair moments | independent opt | gaussian opt | conditional opt |")
    println(io, "|---|---|---|---|---|---|---|")
    for name in sort(collect(keys(n))), variant in ("base", "bus_binaries", "all_binaries")
        k = "$(variant)_order2"
        haskey(o[name], k) && haskey(n[name], k) || continue
        a, b = o[name][k], n[name][k]
        rates = join([@sprintf("%s → %s", pct(a[s]["opt"]), pct(b[s]["opt"])) for s in ("independent", "gaussian", "conditional")], " | ")
        @printf(io, "| %s | %s | %.2f → %.2f | %d/%d | %s |\n", name, variant, a["bound"], b["bound"], b["pair_moments"][1],
            b["pair_moments"][2], rates)
    end
end

println(io, "\n## Experiment 2 (scaling)\n")
println(io, "Gaps of rounded solutions are relative to the best configuration known across old and new runs.\n")
println(io, "| instance | variant | bound old → new | time old → new (s) | best rounded gap old → new | feasible % (cond.) old → new |")
println(io, "|---|---|---|---|---|---|")
for name in ["case14_ots", "case30_uc", "case24_uc", "case30_ots", "case24_ots"]
    runs = Tuple{String,Any,Any}[]
    for pre in ("experiment2_", "experiment2_adjacent_")
        local fo, fn = joinpath(OLD, "$(pre)$(name).json"), joinpath(RES, "$(pre)$(name).json")
        (isfile(fo) && isfile(fn)) && push!(runs, (pre, JSON.parsefile(fo), JSON.parsefile(fn)))
    end
    isempty(runs) && continue
    bk = minimum(min(o["best_found"], n["best_found"]) for (_, o, n) in runs)
    for (pre, o, n) in runs, v in sort(collect(keys(n["relaxations"])))
        haskey(o["relaxations"], v) || continue
        a, b = o["relaxations"][v], n["relaxations"][v]
        bestgap(r) = (bs = filter(!isnothing, [r["schemes"][s]["best"] for s in keys(r["schemes"])]);
            isempty(bs) ? "infeas." : @sprintf("%.2f%%", 100(minimum(bs) - bk) / bk))
        @printf(io, "| %s | %s | %.2f → %.2f | %.1f → %.1f | %s → %s | %s → %s |\n", name, v, a["bound"], b["bound"], a["time"],
            b["time"], bestgap(a), bestgap(b), pct(a["schemes"]["conditional"]["feas"]), pct(b["schemes"]["conditional"]["feas"]))
    end
    @printf(io, "| %s | **best known** | | | %.2f | |\n", name, bk)
end

out = joinpath(RES, "rerun_comparison.md")
write(out, String(take!(io)))
println("wrote ", out)
